apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: ecommerce
data:
  eureka.url: "http://discovery-server:8761/eureka/"
  datasource.url: "jdbc:postgresql://postgres:5432/microservices_pro"
