apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: ecommerce
type: Opaque
data:
  # base64("postgres")
  db-password: cG9zdGdyZXM=
  # base64("microservices-pro-course-secret-key-2024-minimum-256-bits")
  jwt-secret: bWljcm9zZXJ2aWNlcy1wcm8tY291cnNlLXNlY3JldC1rZXktMjAyNC1taW5pbXVtLTI1Ni1iaXRz
