apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-platform.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce-platform.labels" . | nindent 4 }}
data:
  eureka.url: "http://discovery-server:8761/eureka/"
  datasource.url: "jdbc:postgresql://postgres:5432/{{ .Values.infrastructure.postgres.database }}"
  datasource.username: "postgres"
  kafka.bootstrap-servers: "kafka:9092"
  redis.host: "redis"
  redis.port: "6379"
  zipkin.endpoint: "http://zipkin:9411/api/v2/spans"
