apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-platform.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecommerce-platform.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.infrastructure.postgres.password | b64enc | quote }}
  jwt-secret: {{ .Values.global.jwtSecret | b64enc | quote }}
